line-length = 88
target-version = "py312"

[lint]
select = ["E", "F", "I", "B", "UP", "C4", "SIM", "RET", "N"]
ignore = [
  "E203", # compat√≠vel com black
  "E266",
  "E501",
]

[lint.per-file-ignores]
"process/symbiotes/mdd_publisher/scripts/*.py" = ["E402", "RET", "SIM105", "N817", "F821"]
"tests/bdd/*.py" = ["E402"]
[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
