# Symforge project configuration
# Este arquivo foi gerado automaticamente pelo comando `symforge init`.
process: forgeprocess
lib_root: /mnt/c/Users/palha/dev/forge/symforge
created_at: 2025-12-02T13:53:33
